### PR TITLE
Event log in the component playground

### PR DESCRIPTION
**Pull request by dgigafox**
https://github.com/phenixdigital/phx_live_storybook/issues/33

### CODE REVIEW

**Comment by dgigafox** [comment]
@cblavier here's the current flow:
1. Entry LiveView subscribes to the "event_logs" event - this event is broadcast by telemetry whenever a LiveView or component successfully receives a handle_event
2. When Playground Preview LV emits an event, it will be caught by telemetry and broadcast to Entry LV
3. Entry LV will receive a new event and send an update to the playground component
4. Playground component will store all the events it receives thus when this component is re-mounted event logs will be empty again
5. Playground component will display all events

**Comment by cblavier** [comment]
Hey, @dgigafox I just took a few minutes to test your branch.

The "Event Logs"  is indeed populated as LiveView events are emitted, but how can we filter out the events to get only events from the current Playground component? Currently, the event log tabs receive all events (from all components and from all users).

I read [LiveView telemetry documentation](https://hexdocs.pm/telemetry/readme.html) but I could not see any mention of the PID that emitted the event. Any clue?

**Comment by dgigafox** [comment]
@cblavier thanks for checking that out. So to solve this I did the following:
1. Entry live will now subscribe to topic `"event_logs:#{self()}"` where self is the Liveview process. Also, telemetry will broadcast to that topic, where the pid will be from `metadata.socket.root_pid`. I chose root_pid because I think whatever event we will receive, either from preview playground or a live component inside it, the root_pid will still be entry live's pid
2. If the event is of type component and its parent pid is playground preview pid, then it should be an event from a component inside the playground preview. So we catch it.
3. If the event is of type live_view and its view is PlaygroundPreviewLive, then it should be an event from a functional component inside the playground preview. So we catch it.

What do you think?

**Comment by cblavier** [comment]
Seems like a good idea to me 👍 
Please go on!

**Comment by dgigafox** [comment]
@cblavier I was wrong with number 2. Parent PID of a live component mounted inside playground preview is still the entry LiveView PID. So in short as long as the event is from PlaygroundPreviewLive then we log it.

I'm kind of stuck on how are we going to display the event. Here's a sample from JS storybook
Screen Shot 2022-09-04 at 4 33 32 PM
Could you please give me a sample of how you envision it?

**Comment by cblavier** [comment]
I just sketched this, feedbacks are welcome!

CleanShot 2022-09-04 at 11 02 12

**Comment by dgigafox** [comment]
@cblavier Does this display of data work for you?
For liveview event
Screen Shot 2022-09-11 at 10 52 25 PM

For component event
Screen Shot 2022-09-11 at 10 51 58 PM

Also, do you think a badge of unread events is needed? Cause I am thinking just displaying it as `Event Logs (n)` will do where `n` is just the count of events triggered. This is how it is written in JS Storybook but what do you think?

**Comment by cblavier** [comment]
This is looking great!

For the badge, you can keep it simple for now (text only), and I may try something with a badge later (but I may be too much indeed)

I think you can switch logs to a monospace font (I think if you wrap it in  `<code class="lsb">...</code>`, you'll get the Tailwind monospace font)

I'll give you further feedback after I tried your branch

**Comment by cblavier** [comment]
Hey Darren, your code is really clean and the tests are 👌
I may do a few adjustments, _UI wise_, but the foundations are strong!

Thank you for your help 🔥

**Pull request merged**
