### PR TITLE
Switched to exs files for entries

### PR DESCRIPTION
**Pull request by cblavier**
This is working fine, but I may have missed the objective because if I run an iex shell on my app, it seems that my components entries are still available as modules.

Any thoughts @LostKobrakai?

### CODE REVIEW

**Comment by LostKobrakai** [comment]
When are the `.exs` files evaluated? At compile time or at runtime? If at runtime then their modules will be available, but only after the code runs, which evaluates them. When storybook is not included (e.g. in prod) then those modules should not be evaluated and therefore not available.

**Comment by cblavier** [comment]
It’s performed at compile time.  
I require the file, fetches its content, and then unrequire it. 

I tried to iex into a running mix release, the module was available 🤷‍♂️

**Comment by LostKobrakai** [comment]
What do you do with the contents?

**Comment by cblavier** [comment]
Il build a struct from it: https://github.com/phenixdigital/phx_live_storybook/blob/8b60207c8099a7dd62ecf6493d0d1737cc29e162/lib/phx_live_storybook/entries.ex#L106

The idea is that after this compilation step, I only rely on structs. I no longer use the module defined in exs

**Comment by LostKobrakai** [comment]
Hmm that should be fine then. I'm out of more advice without digging deeper.

**Comment by cblavier** [comment]
I will dig then!
https://hexdocs.pm/elixir/1.12/Code.html#require_file/2 is the good choice?

**Comment by LostKobrakai** [comment]
Maybe try `Code.eval_file`, though I'm really fuzzy on how exactly they're different.

**Comment by cblavier** [comment]
So I switched to `Code.eval_file`, but it made no difference.
I will merge this PR anyway, as I think is code is better now with a better separation of compilation / runtime

**Pull request merged**
